version: '3.7'

services: 
    web:
        build: ./loog/ 
        entrypoint: ./entrypoint.sh
        command: gunicorn loog.wsgi:application --bind 0.0.0.0:8000
        volumes: 
            - ./loog/:/usr/src/loog/
            - static_volume:/usr/apps/loog/static
            - media_volume:/usr/apps/loog/media
        expose: 
            - 8000
        env_file: 
            - ./.env
        restart: always
        depends_on: 
            - db
            - redis
    db:
        image: mysql:8.0
        expose: 
            - 3306
        restart: always
        env_file: 
            - ./.env
    nginx:
        build: ./nginx
        restart: always
        ports:
            - 80:80
        depends_on:
            - web
        volumes: 
            - static_volume:/usr/apps/loog/static
            - media_volume:/usr/apps/loog/media
    redis:
        image: redis:alpine
    celery:
        build: ./loog
        command: celery -A loog worker -l info
        volumes:
            - ./loog/:/usr/src/loog/
        env_file: 
            - ./.env
        depends_on: 
            - redis
    celery-beat:
        build: ./loog
        command: celery -A loog beat -l info
        volumes:
            - ./loog/:/usr/src/app/
        env_file: 
            - ./.env
        depends_on:
            - redis



volumes: 
    static_volume:
    media_volume:
